inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks
doc-warnings: true

ignore-paths:
  - scan_to_paperless/process_schema.py
  - scan_to_paperless/config.py

pydocstyle:
  disable:
    - D212 # Multi-line docstring summary should start at the first line
    - D203 # 1 blank line required before class docstring (found 0), not compatible with Black
    - D202 # No blank lines allowed after function docstring

pylint:
  disable:
    - broad-exception-caught
  options:
    good-names: x,y

bandit:
  options:
    config: .bandit.yaml
