inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - utils:unsafe

ignore-paths:
  - scan_to_paperless/process_schema.py
  - scan_to_paperless/config.py

pylint:
  disable:
    - broad-exception-caught
  options:
    good-names: x,y

mypy:
  options:
    python-version: '3.10'

ruff:
  options:
    target-version: py310
