inherits:
  - duplicated
  - utils:base
  - utils:no-design-checks
  - utils:fix

ignore-paths:
  - scan_to_paperless/process_schema.py
  - scan_to_paperless/config.py

ignore-patterns:
  - .*/test_.*

pylint:
  disable:
    - broad-exception-caught
    - no-member
    - no-name-in-module
  options:
    good-names: x,y

mypy:
  options:
    python-version: '3.11'

ruff:
  options:
    target-version: py311
