---
strictness: veryhigh
doc-warnings: true
max-line-length: 110

ignore-paths:
  - scan_to_paperless/process_schema.py
  - scan_to_paperless/config.py

pep8:
  disable:
    - E203 # whitespace before ':'

pep257:
  disable:
    - D212 # Multi-line docstring summary should start at the first line
    - D203 # 1 blank line required before class docstring (found 0), not compatible with Black

pylint:
  disable:
    - wrong-import-order
    - line-too-long
    - no-value-for-parameter
    - too-few-public-methods
    - too-many-lines
    - too-many-branches
    - too-many-statements
    - too-many-locals
    - too-many-nested-blocks
    - too-many-arguments
    - broad-except
  options:
    good-names: x,y
    py-version: '3.8'

bandit:
  run: true
  options:
    config: .bandit.yaml

mypy:
  run: true

mccabe:
  run: false

pyroma:
  run: true
