#!/usr/bin/env python3

import os
import subprocess  # nosec

import pkg_resources


def main() -> None:
    with open("requirements.txt", encoding="utf-8") as requirements_txt:
        requirements = {
            requirement.key: requirement for requirement in pkg_resources.parse_requirements(requirements_txt)
        }

    version = requirements["jsonschema-gentypes"].specs[0][1]
    subprocess.check_call(
        [
            "docker",
            "run",
            "--rm",
            f"--user={os.getuid()}",
            f"--volume={os.getcwd()}:/src",
            f"camptocamp/jsonschema-gentypes:{version}",
        ]
    )


if __name__ == "__main__":
    main()
