#!/usr/bin/env python3

import configparser
import os
import subprocess  # nosec


def main() -> None:
    pipfile = configparser.ConfigParser()
    pipfile.read("Pipfile")
    version = pipfile["packages"]["jsonschema-gentypes"].strip('"=>')
    subprocess.check_call(
        [
            "docker",
            "run",
            "--rm",
            f"--user={os.getuid()}",
            f"--volume={os.getcwd()}:/src",
            f"camptocamp/jsonschema-gentypes:{version}",
        ]
    )


if __name__ == "__main__":
    main()
