name: Pull request check

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - edit
      - synchronize

jobs:
  build:
    name: Pull request check
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - run: python3 -m pip install --user codespell
      - name: Check pull request
        run: ci/check-pull-request
        env:
          GITHUB_EVENT: ${{ toJson(github) }}
